// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqdm4aCkVLpJjTfjYEmkMg2Rh5zbt4Sg',
    appId: '1:376711787348:web:f34a59549c19fafc290ec1',
    messagingSenderId: '376711787348',
    projectId: 'zeus-smart-city',
    authDomain: 'zeus-smart-city.firebaseapp.com',
    storageBucket: 'zeus-smart-city.firebasestorage.app',
    measurementId: 'G-D1TNLCFQ58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUxSaxP2WkI_r9qlbfDnc7v0Yr-EqbkSw',
    appId: '1:376711787348:android:1c25e5c3d12413b6290ec1',
    messagingSenderId: '376711787348',
    projectId: 'zeus-smart-city',
    storageBucket: 'zeus-smart-city.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvaNRXo9RjGFBwjwiHxgPa8mpyQI8N3bI',
    appId: '1:376711787348:ios:f523b6bb45520cbc290ec1',
    messagingSenderId: '376711787348',
    projectId: 'zeus-smart-city',
    storageBucket: 'zeus-smart-city.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
